name: build-release
on:
    push:
        paths:
            - version.json
    workflow_dispatch:

jobs:
    build:
        if: github.ref == 'refs/heads/master'
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 1
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, windows-latest ]
                php-versions: [ '7.4' ]

        steps:
            -   uses: actions/checkout@v2
            -   name: read-release-version
            -   uses: HardNorth/github-version-generate@v1.1.1
            -   with:
                    version-source: file
                    version-file: version.json
                    version-file-extraction-pattern: '(?<=version=).+'
            -   name: print-version
                run: echo "Releasing $CURRENT_VERSION"
            -   name: Setup PHP 7.4
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: fileinfo
                    coverage: none
            -   name: Installed versions
                run: php -v
            -   name: Install Composer dependencies
                uses: ramsey/composer-install@v1
            -   name: Run phpstan
                run: vendor/bin/phpstan analyse --no-progress
            -   name: Run phpunit
                env:
                    CHECKOUT_SECRET_KEY: ${{ secrets.IT_CHECKOUT_SECRET_KEY }}
                    CHECKOUT_PUBLIC_KEY: ${{ secrets.IT_CHECKOUT_PUBLIC_KEY }}
                    CHECKOUT_FOUR_SECRET_KEY: ${{ secrets.IT_CHECKOUT_FOUR_SECRET_KEY }}
                    CHECKOUT_FOUR_PUBLIC_KEY: ${{ secrets.IT_CHECKOUT_FOUR_PUBLIC_KEY }}
                    CHECKOUT_FOUR_OAUTH_CLIENT_ID: ${{ secrets.IT_CHECKOUT_FOUR_OAUTH_CLIENT_ID }}
                    CHECKOUT_FOUR_OAUTH_CLIENT_SECRET: ${{ secrets.IT_CHECKOUT_FOUR_OAUTH_CLIENT_SECRET }}
                run: vendor/bin/phpunit --verbose --testdox
            -   name: create-release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ env.CURRENT_VERSION }}
                    release_name: ${{ env.CURRENT_VERSION }}
                    body: ${{ github.event.head_commit.message }}
                    draft: false
                    prerelease: false
