name: build-pull-request
on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 1
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, windows-latest ]
                php-versions: [ '7.4' ]

        steps:
            -   uses: actions/checkout@v2
            -   name: Setup PHP 7.4
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: fileinfo
                    coverage: none
            -   name: Installed versions
                run: php -v
            -   name: Install Composer dependencies
                uses: ramsey/composer-install@v1
            -   name: Run phpstan
                run: vendor/bin/phpstan analyse --no-progress


