name: build-release
on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup PHP 7.4
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'
                    extensions: fileinfo
                    coverage: none
            -   name: Installed versions
                run: php -v
            -   name: Install Composer dependencies
                uses: ramsey/composer-install@v1
            -   name: Run phpstan
                run: vendor/bin/phpstan analyse --no-progress
            -   name: Read Release version
                uses: HardNorth/github-version-generate@v1.1.1
                with:
                    version-source: file
                    version-file: 'version.json'
                    version-file-extraction-pattern: '"version":\s*"([^"]+)"'
            -   name: Print Release version
                run: echo "Releasing $CURRENT_VERSION"
            -   name: create-release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ env.CURRENT_VERSION }}
                    release_name: ${{ env.CURRENT_VERSION }}
                    body: ${{ github.event.head_commit.message }}
                    draft: false
                    prerelease: false
